using UnityEngine;
using System.Collections;
using System;
using System.Collections.Generic;

[ExecuteInEditMode]
public class LocalizationManager : MonoBehaviour
{
    public static Dictionary<string, string> LocalizeDictionary = new Dictionary<string, string>();
    public static HashSet<string> localizeIDs = new HashSet<string>();
    public delegate void ChangeLanguage();
    public static event ChangeLanguage OnChangeLanguage;

    class LocalizationData
    {
        public string id { get; set; }
        public string value { get; set; }
    }

    public static void CallChangeLanguage()
    {
        if (OnChangeLanguage != null)
            OnChangeLanguage();
    }

    public static void RefreshIDS()
    {
        localizeIDs.Add("account_4_char");
        localizeIDs.Add("account_name");
        localizeIDs.Add("account_special_char");
        localizeIDs.Add("add_to_inventory");
        localizeIDs.Add("autumn_tribunal_upper");
        localizeIDs.Add("blessing_continue");
        localizeIDs.Add("blessing_grant");
        localizeIDs.Add("blessing_honor");
        localizeIDs.Add("blessing_message");
        localizeIDs.Add("blessing_offices");
        localizeIDs.Add("blessing_pop");
        localizeIDs.Add("bos_elixir");
        localizeIDs.Add("bos_elixir_back");
        localizeIDs.Add("bos_elixir_potion");
        localizeIDs.Add("bos_title");
        localizeIDs.Add("card_spirit_attack_upper");
        localizeIDs.Add("card_spirit_behavior_desc");
        localizeIDs.Add("card_spirit_behavior_upper");
        localizeIDs.Add("card_spirit_coven_upper");
        localizeIDs.Add("card_spirit_desc_upper");
        localizeIDs.Add("card_spirit_reward_desc");
        localizeIDs.Add("card_spirit_reward_upper");
        localizeIDs.Add("card_spirit_summoner_upper");
        localizeIDs.Add("card_witch_cast");
        localizeIDs.Add("card_witch_cast_upper");
        localizeIDs.Add("card_witch_dominion");
        localizeIDs.Add("card_witch_domRank");
        localizeIDs.Add("card_witch_energy");
        localizeIDs.Add("card_witch_grey");
        localizeIDs.Add("card_witch_level");
        localizeIDs.Add("card_witch_noCoven");
        localizeIDs.Add("card_witch_shadow");
        localizeIDs.Add("card_witch_white");
        localizeIDs.Add("card_witch_worldRank");
        localizeIDs.Add("cast_crit");
        localizeIDs.Add("cast_death");
        localizeIDs.Add("cast_energy");
        localizeIDs.Add("cast_grey");
        localizeIDs.Add("cast_level");
        localizeIDs.Add("cast_screen_no_coven");
        localizeIDs.Add("cast_screen_request");
        localizeIDs.Add("cast_shadow");
        localizeIDs.Add("cast_spirit_greater");
        localizeIDs.Add("cast_spirit_legendary");
        localizeIDs.Add("cast_spirit_lesser");
        localizeIDs.Add("cast_spirit_superior");
        localizeIDs.Add("cast_spirit_type");
        localizeIDs.Add("cast_white");
        localizeIDs.Add("cast_you");
        localizeIDs.Add("change_wardrobe");
        localizeIDs.Add("character_4_char");
        localizeIDs.Add("character_empty");
        localizeIDs.Add("character_name");
        localizeIDs.Add("character_taken");
        localizeIDs.Add("chat_coven");
        localizeIDs.Add("chat_degree");
        localizeIDs.Add("chat_dominion");
        localizeIDs.Add("chat_go_to_location");
        localizeIDs.Add("chat_grey");
        localizeIDs.Add("chat_news");
        localizeIDs.Add("chat_settings");
        localizeIDs.Add("chat_shadow");
        localizeIDs.Add("chat_share_location");
        localizeIDs.Add("chat_shout");
        localizeIDs.Add("chat_shoutMessage");
        localizeIDs.Add("chat_state_trouble");
        localizeIDs.Add("chat_time_ago_days");
        localizeIDs.Add("chat_time_ago_mins");
        localizeIDs.Add("chat_time_ago_seconds");
        localizeIDs.Add("chat_time_ago_weeks");
        localizeIDs.Add("chat_time_ago_years");
        localizeIDs.Add("chat_translate");
        localizeIDs.Add("chat_white");
        localizeIDs.Add("chat_world");
        localizeIDs.Add("choose_gender");
        localizeIDs.Add("choose_upper");
        localizeIDs.Add("collect");
        localizeIDs.Add("collecting");
        localizeIDs.Add("contact_support");
        localizeIDs.Add("contact_support_upper");
        localizeIDs.Add("continue_generic");
        localizeIDs.Add("continue_upper");
        localizeIDs.Add("continue_without_tutorial");
        localizeIDs.Add("coven_invite_choose");
        localizeIDs.Add("coven_invite_continue");
        localizeIDs.Add("coven_invite_enter_text");
        localizeIDs.Add("coven_screen_allied");
        localizeIDs.Add("coven_screen_coven_allied");
        localizeIDs.Add("coven_screen_create");
        localizeIDs.Add("coven_screen_invite");
        localizeIDs.Add("coven_screen_level");
        localizeIDs.Add("coven_screen_name");
        localizeIDs.Add("coven_screen_nothing");
        localizeIDs.Add("coven_screen_request");
        localizeIDs.Add("create_upper");
        localizeIDs.Add("daily_event_log");
        localizeIDs.Add("daily_explore");
        localizeIDs.Add("daily_gather");
        localizeIDs.Add("daily_hide");
        localizeIDs.Add("daily_spell");
        localizeIDs.Add("daily_spell_completion");
        localizeIDs.Add("daily_spell_title");
        localizeIDs.Add("daily_tap_chest");
        localizeIDs.Add("daily_title");
        localizeIDs.Add("days_remain");
        localizeIDs.Add("dominion_location");
        localizeIDs.Add("download");
        localizeIDs.Add("email");
        localizeIDs.Add("empty_email");
        localizeIDs.Add("enter_code_upper");
        localizeIDs.Add("enter_digit_code_email");
        localizeIDs.Add("enter_password_upper");
        localizeIDs.Add("female");
        localizeIDs.Add("flight_physical_form");
        localizeIDs.Add("flight_spirit_form");
        localizeIDs.Add("forgot_password");
        localizeIDs.Add("ftf_her");
        localizeIDs.Add("ftf_him");
        localizeIDs.Add("ftf_he");
        localizeIDs.Add("ftf_she");
        localizeIDs.Add("ftf_his");
        localizeIDs.Add("ftf_summer");
        localizeIDs.Add("ftf_winter");
        localizeIDs.Add("ftf_autumn");
        localizeIDs.Add("ftf_spring");
        localizeIDs.Add("generic_no");
        localizeIDs.Add("generic_yes");
        localizeIDs.Add("help_call_crows");
        localizeIDs.Add("help_call_crows_confirm");
        localizeIDs.Add("help_logged_in");
        localizeIDs.Add("incorrect_username");
        localizeIDs.Add("internet_error");
        localizeIDs.Add("invalid_char");
        localizeIDs.Add("leveled_continue");
        localizeIDs.Add("leveled_number");
        localizeIDs.Add("leveled_up");
        localizeIDs.Add("loading");
        localizeIDs.Add("location_error");
        localizeIDs.Add("login_back");
        localizeIDs.Add("login_create_appropriate");
        localizeIDs.Add("login_past_player_account");
        localizeIDs.Add("login_welcome_witch");
        localizeIDs.Add("male");
        localizeIDs.Add("name");
        localizeIDs.Add("no_email");
        localizeIDs.Add("tip");
        localizeIDs.Add("original_sound");
        localizeIDs.Add("password");
        localizeIDs.Add("password_4_char");
        localizeIDs.Add("pop_required_ingredients");
        localizeIDs.Add("pop_add_ingredients");
        localizeIDs.Add("pop_owner_coven");
        localizeIDs.Add("pop_owner_player");
        localizeIDs.Add("pop_unclaimed");
        localizeIDs.Add("pop_hint");
        localizeIDs.Add("pop_full");
        localizeIDs.Add("pop_enter");
        localizeIDs.Add("pop_enter_no");
        localizeIDs.Add("pop_title");
        localizeIDs.Add("portal_cast");
        localizeIDs.Add("portal_energy_channel");
        localizeIDs.Add("portal_fly_to");
        localizeIDs.Add("portal_ingredient_add");
        localizeIDs.Add("portal_ingredient_used");
        localizeIDs.Add("portal_last_attacked");
        localizeIDs.Add("portal_type_lesser");
        localizeIDs.Add("portal_not_enough");
        localizeIDs.Add("portal_summon_in");
        localizeIDs.Add("portal_summon_spirit");
        localizeIDs.Add("portal_time_hour");
        localizeIDs.Add("portal_time_minute");
        localizeIDs.Add("portal_time_second");
        localizeIDs.Add("portal_create");
        localizeIDs.Add("portal_time_remaining");
        localizeIDs.Add("portal_destroy");
        localizeIDs.Add("portal_trace");
        localizeIDs.Add("privacy_policy");
        localizeIDs.Add("raincrow_studios");
        localizeIDs.Add("re_enter_password");
        localizeIDs.Add("reset");
        localizeIDs.Add("reset_account_name");
        localizeIDs.Add("reset_bad_code");
        localizeIDs.Add("reset_button");
        localizeIDs.Add("reset_enter_code");
        localizeIDs.Add("reset_password");
        localizeIDs.Add("reset_upper");
        localizeIDs.Add("reset_user_invalid");
        localizeIDs.Add("savannah_upper");
        localizeIDs.Add("school_skip");
        localizeIDs.Add("school_title");
        localizeIDs.Add("school_watch");
        localizeIDs.Add("server_down_bottom");
        localizeIDs.Add("server_down_top");
        localizeIDs.Add("server_syncing");
        localizeIDs.Add("sign_in");
        localizeIDs.Add("sign_in_existing");
        localizeIDs.Add("spell_alignment_change");
        localizeIDs.Add("spell_cancel");
        localizeIDs.Add("spell_bind");
        localizeIDs.Add("spell_cast");
        localizeIDs.Add("spell_cast_attacked");
        localizeIDs.Add("spell_cast_backfire");
        localizeIDs.Add("spell_cast_backfire_yours");
        localizeIDs.Add("spell_cast_cancel");
        localizeIDs.Add("spell_cast_success");
        localizeIDs.Add("spell_cast_summon");
        localizeIDs.Add("spell_clear_gem");
        localizeIDs.Add("spell_clear_herb");
        localizeIDs.Add("spell_clear_tool");
        localizeIDs.Add("spell_cost");
        localizeIDs.Add("spell_dead");
        localizeIDs.Add("spell_degree_gray");
        localizeIDs.Add("spell_degree_shadow");
        localizeIDs.Add("spell_degree_white");
        localizeIDs.Add("spell_empower");
        localizeIDs.Add("spell_escape_upper");
        localizeIDs.Add("spell_fail");
        localizeIDs.Add("spell_fail_yours");
        localizeIDs.Add("spell_fizzle");
        localizeIDs.Add("spell_fizzle_yours");
        localizeIDs.Add("spell_immune");
        localizeIDs.Add("spell_immune_to_you");
        localizeIDs.Add("spell_increase");
        localizeIDs.Add("spell_ingredient_for_me");
        localizeIDs.Add("spell_ingredient_tap_choose");
        localizeIDs.Add("spell_ingredient_wise");
        localizeIDs.Add("spell_invalid");
        localizeIDs.Add("spell_sig_discover");
        localizeIDs.Add("spell_tap_ingredient_add");
        localizeIDs.Add("spell_tap_tool_title");
        localizeIDs.Add("spell_xp");
        localizeIDs.Add("spirit_active");
        localizeIDs.Add("spirit_active_none");
        localizeIDs.Add("spirit_deck_expire");
        localizeIDs.Add("spirit_deck_fly_to");
        localizeIDs.Add("spirit_deck_ingredients");
        localizeIDs.Add("spirit_deck_none");
        localizeIDs.Add("spirit_deck_unknown");
        localizeIDs.Add("spirit_deck_xp_gained");
        localizeIDs.Add("spirit_discover_date");
        localizeIDs.Add("spirit_gain");
        localizeIDs.Add("spirit_known");
        localizeIDs.Add("spirit_known_none");
        localizeIDs.Add("spirit_portal");
        localizeIDs.Add("spirit_portal_none");
        localizeIDs.Add("spirit_use_tool");
        localizeIDs.Add("spirit_was_banished");
        localizeIDs.Add("spring_tribunal_upper");
        localizeIDs.Add("start_new");
        localizeIDs.Add("store_accept");
        localizeIDs.Add("store_balance");
        localizeIDs.Add("store_bought_drachs_upper");
        localizeIDs.Add("store_buy");
        localizeIDs.Add("store_buy_gold");
        localizeIDs.Add("store_buy_silver");
        localizeIDs.Add("store_buy_upper");
        localizeIDs.Add("store_cancel_upper");
        localizeIDs.Add("store_confirm_upper");
        localizeIDs.Add("store_cost");
        localizeIDs.Add("store_current");
        localizeIDs.Add("store_elixir");
        localizeIDs.Add("store_elixir_more");
        localizeIDs.Add("store_elixir_upper");
        localizeIDs.Add("store_gear");
        localizeIDs.Add("store_gear_accessories");
        localizeIDs.Add("store_gear_clothing");
        localizeIDs.Add("store_gear_hairstyle");
        localizeIDs.Add("store_gear_or");
        localizeIDs.Add("store_gear_or_upper");
        localizeIDs.Add("store_gear_owned_upper");
        localizeIDs.Add("store_gear_skin_art");
        localizeIDs.Add("store_gear_unlock_upper");
        localizeIDs.Add("store_gear_unlocked_upper");
        localizeIDs.Add("store_gear_upper");
        localizeIDs.Add("store_more_silver");
        localizeIDs.Add("store_not_enough_gold");
        localizeIDs.Add("store_not_enough_silver");
        localizeIDs.Add("store_preview");
        localizeIDs.Add("store_purchase_successful");
        localizeIDs.Add("store_purchase_unsuccessful");
        localizeIDs.Add("store_silver");
        localizeIDs.Add("store_silver_drachs_upper");
        localizeIDs.Add("store_silver_no_buy");
        localizeIDs.Add("store_silver_upper");
        localizeIDs.Add("strongest_coven_dominion");
        localizeIDs.Add("strongest_witch_dominion");
        localizeIDs.Add("summer_tribunal_upper");
        localizeIDs.Add("summoning_add_gems_botanicals");
        localizeIDs.Add("summoning_botanicals_upper");
        localizeIDs.Add("summoning_cast_upper");
        localizeIDs.Add("summoning_clear");
        localizeIDs.Add("summoning_created_by");
        localizeIDs.Add("summoning_destroy");
        localizeIDs.Add("summoning_empower");
        localizeIDs.Add("summoning_gems_upper");
        localizeIDs.Add("summoning_please_select");
        localizeIDs.Add("summoning_portal");
        localizeIDs.Add("summoning_portal_attack");
        localizeIDs.Add("summoning_portal_summon_time");
        localizeIDs.Add("summoning_select_tool");
        localizeIDs.Add("summoning_spirit_summon_time");
        localizeIDs.Add("summoning_tools_upper");
        localizeIDs.Add("summoning_trace_circle");
        localizeIDs.Add("update_app");
        localizeIDs.Add("username_taken");
        localizeIDs.Add("winter_tribunal_upper");
        localizeIDs.Add("witch_name");
        localizeIDs.Add("witch_school_title");
        localizeIDs.Add("invite_send");
        localizeIDs.Add("invite_failed");
        localizeIDs.Add("invite_coven");
        localizeIDs.Add("ftf_you_map");
        localizeIDs.Add("ftf_gained_power");
        localizeIDs.Add("ftf_known_spirits");
        localizeIDs.Add("ftf_active_spirits");
        localizeIDs.Add("ftf_active_portals");
        localizeIDs.Add("ftf_reward_upper");
        localizeIDs.Add("ftf_reward_capture");
        localizeIDs.Add("ftf_behavior_upper");
        localizeIDs.Add("ftf_description_upper");
        localizeIDs.Add("ftf_wild_spirit");
        localizeIDs.Add("ftf_attack_button");
        localizeIDs.Add("ftf_brigid_degree_upper");
        localizeIDs.Add("ftf_brigid_school_upper");
        localizeIDs.Add("ftf_invite_to_coven");
        localizeIDs.Add("ftf_theo_consume");
        localizeIDs.Add("ftf_silenced_by");
        localizeIDs.Add("ftf_silenced");
        localizeIDs.Add("ftf_dispel");
        localizeIDs.Add("ftf_silence_dispel");
        localizeIDs.Add("ftf_died");
        localizeIDs.Add("ftf_banish_brigid");
        localizeIDs.Add("ftf_banish");
        localizeIDs.Add("ftf_claim");
        localizeIDs.Add("ftf_buy_silver");
        localizeIDs.Add("ftf_not_enough");
        localizeIDs.Add("ftf_continue");
        localizeIDs.Add("ftf_success");
        localizeIDs.Add("ftf_show_school");
        localizeIDs.Add("ftf_no_education");
        localizeIDs.Add("ftf_continue_game");
        localizeIDs.Add("ftf_cast_button");
        localizeIDs.Add("ftf_immune_upper");
        localizeIDs.Add("ftf_brigid");
        localizeIDs.Add("ftf_barghest_tier");
        localizeIDs.Add("ftf_barghest");
        localizeIDs.Add("ftf_world_upper");
        localizeIDs.Add("ftf_barghest_type");
        localizeIDs.Add("ftf_barghest_behavior");
        localizeIDs.Add("ftf_barghest_behavior_detailed");
        localizeIDs.Add("ftf_barghest_description");
        localizeIDs.Add("ftf_barghest_tier_one");
        localizeIDs.Add("ftf_barghest_lesser");
        localizeIDs.Add("ftf_barghest_wild");
        localizeIDs.Add("ftf_world");
        localizeIDs.Add("ftf_one");
        localizeIDs.Add("ftf_eight");
        localizeIDs.Add("ftf_brigid_energy");
        localizeIDs.Add("ftf_cast_dusk");
        localizeIDs.Add("ftf_buy_best");
        localizeIDs.Add("ftf_brigid_mad");
        localizeIDs.Add("ftf_best_description");
        localizeIDs.Add("ftf_best_cost");
        localizeIDs.Add("ftf_best");
        localizeIDs.Add("character_signature_new");
        localizeIDs.Add("spell_cast_success_yours");
        localizeIDs.Add("spell_cast_energy_sap");
        localizeIDs.Add("spell_cast_backfire_theirs");
        localizeIDs.Add("spirit_banished");
        localizeIDs.Add("lt_energy");
        localizeIDs.Add("lt_none");
        localizeIDs.Add("lt_portal");
        localizeIDs.Add("lt_summon_in");
        localizeIDs.Add("lt_level");
        localizeIDs.Add("lt_dominion");
        localizeIDs.Add("lt_dominion_rank");
        localizeIDs.Add("lt_world_rank");
        localizeIDs.Add("lt_coven");
        localizeIDs.Add("lt_invite_sent");
        localizeIDs.Add("lt_invite_sent_already");
        localizeIDs.Add("pop_defended");
        localizeIDs.Add("lt_spirit_s");
        localizeIDs.Add("lt_spirit_p");
        localizeIDs.Add("lt_close");
        localizeIDs.Add("pop_treasure_time");
        localizeIDs.Add("lt_silenced");
        localizeIDs.Add("lt_time_days");
        localizeIDs.Add("lt_time_day");
        localizeIDs.Add("lt_time_hours");
        localizeIDs.Add("lt_time_hour");
        localizeIDs.Add("lt_time_minutes");
        localizeIDs.Add("lt_unkown");
        localizeIDs.Add("lt_time_minute");
        localizeIDs.Add("lt_time_seconds");
        localizeIDs.Add("lt_time_secs");
        localizeIDs.Add("server_connect");
        localizeIDs.Add("store_buy_energy");
        localizeIDs.Add("consume_amount");
        localizeIDs.Add("show_dominion");
        localizeIDs.Add("blessing_time");
        localizeIDs.Add("ingredient_gems");
        localizeIDs.Add("ingredient_botanicals");
        localizeIDs.Add("ingredient_tools");
        localizeIDs.Add("spell_tap_herbs_none");
        localizeIDs.Add("spell_tap_tools_none");
        localizeIDs.Add("spell_tap_gems_none");
        localizeIDs.Add("chat_player_level");
        localizeIDs.Add("chat_translate_language");
        localizeIDs.Add("lt_failed");
        localizeIDs.Add("chat_screen_no_coven");
        localizeIDs.Add("invite_request");
        localizeIDs.Add("coven_create_name_used");
        localizeIDs.Add("coven_create_name_invalid");
        localizeIDs.Add("coven_create_name_empty");
        localizeIDs.Add("coven_request_name");
        localizeIDs.Add("coven_request_success");
        localizeIDs.Add("coven_request_sent");
        localizeIDs.Add("coven_request_full");
        localizeIDs.Add("coven_request_null");
        localizeIDs.Add("coven_invite");
        localizeIDs.Add("coven_invite_success");
        localizeIDs.Add("coven_invite_sent");
        localizeIDs.Add("coven_invite_null");
        localizeIDs.Add("coven_null_authorized");
        localizeIDs.Add("coven_invite_empty");
        localizeIDs.Add("coven_invite_join");
        localizeIDs.Add("coven_invite_join_success");
        localizeIDs.Add("coven_invite_cancelled");
        localizeIDs.Add("coven_disbanded");
        localizeIDs.Add("coven_decline_invite");
        localizeIDs.Add("coven_decline_invite_success");
        localizeIDs.Add("coven_invite_cancel");
        localizeIDs.Add("coven_invite_cancel_success");
        localizeIDs.Add("coven_leave");
        localizeIDs.Add("coven_leave_success");
        localizeIDs.Add("coven_disband");
        localizeIDs.Add("coven_disband_success");
        localizeIDs.Add("coven_member_promote");
        localizeIDs.Add("coven_member_promote_success");
        localizeIDs.Add("coven_member_remove");
        localizeIDs.Add("coven_member_remove_success");
        localizeIDs.Add("coven_motto");
        localizeIDs.Add("coven_motto_set");
        localizeIDs.Add("pop_rewards_silver");
        localizeIDs.Add("pop_rewards_gold");
        localizeIDs.Add("pop_rewards_energy");
        localizeIDs.Add("header_pop");
        localizeIDs.Add("header_invites_players");
        localizeIDs.Add("header_requests");
        localizeIDs.Add("header_allies");
        localizeIDs.Add("header_allied");
        localizeIDs.Add("header_invites");
        localizeIDs.Add("header_no_coven");
        localizeIDs.Add("ui_drink_potion");
        localizeIDs.Add("apparel_head");
        localizeIDs.Add("apparel_hair");
        localizeIDs.Add("apparel_neck");
        localizeIDs.Add("apparel_chest");
        localizeIDs.Add("apparel_wrist");
        localizeIDs.Add("apparel_hands");
        localizeIDs.Add("apparel_legs");
        localizeIDs.Add("apparel_feet");
        localizeIDs.Add("apparel_carry");
        localizeIDs.Add("apparel_tattoo");
        localizeIDs.Add("rarity_common");
        localizeIDs.Add("rarity_less");
        localizeIDs.Add("rarity_rare");
        localizeIDs.Add("rarity_exotic");
        localizeIDs.Add("rarity_num");
        localizeIDs.Add("add_to_inventory_fail");
        localizeIDs.Add("inventory_tool");
        localizeIDs.Add("inventory_missing");
        localizeIDs.Add("summoning_success");
        localizeIDs.Add("summoning_time");
        localizeIDs.Add("error_unknown");
        localizeIDs.Add("spell_player_immune");
        localizeIDs.Add("kyteler_owned");
        localizeIDs.Add("kyteler_last_location");
        localizeIDs.Add("kyteler_date_discovered");
        localizeIDs.Add("leaderboard_coven");
        localizeIDs.Add("leaderboard_player");
        localizeIDs.Add("location_owned");
        localizeIDs.Add("location_unclaimed");
        localizeIDs.Add("login_error");
        localizeIDs.Add("login_retry");
        localizeIDs.Add("account_creation_username_invalid");
        localizeIDs.Add("account_creation_session_expired");
        localizeIDs.Add("account_creation_email_invalid");
        localizeIDs.Add("account_creation_error");
        localizeIDs.Add("character_special_char");
        localizeIDs.Add("character_name_invalid");
        localizeIDs.Add("character_error");
        localizeIDs.Add("password_no_match");
        localizeIDs.Add("ui_response_spell");
        localizeIDs.Add("ui_response_portal");
        localizeIDs.Add("ui_response_move_closer");
        localizeIDs.Add("ui_response_summon");
        localizeIDs.Add("ui_response_backfire");
        localizeIDs.Add("ui_response_shadow");
        localizeIDs.Add("ui_response_white");
        localizeIDs.Add("ui_response_grey");
        localizeIDs.Add("ui_response_witch");
        localizeIDs.Add("ui_response_spirit");
        localizeIDs.Add("ui_response_spirit_discovered");
        localizeIDs.Add("ui_response_discovered");
        localizeIDs.Add("spell_target");
        localizeIDs.Add("spell_target_lose_energy");
        localizeIDs.Add("spell_target_gain_energy");
        localizeIDs.Add("attacked_message");
        localizeIDs.Add("attacked_spirit");
        localizeIDs.Add("item_loading");
        localizeIDs.Add("moon_rise");
        localizeIDs.Add("moon_new");
        localizeIDs.Add("moon_wax_cresc");
        localizeIDs.Add("moon_first_quart");
        localizeIDs.Add("moon_wax_gib");
        localizeIDs.Add("moon_full");
        localizeIDs.Add("moon_wan_gib");
        localizeIDs.Add("moon_last_quart");
        localizeIDs.Add("moon_wan_cresc");
        localizeIDs.Add("moon_relation");
        localizeIDs.Add("moon_desc");
        localizeIDs.Add("moon_energy");
        localizeIDs.Add("log_blessing_savannah");
        localizeIDs.Add("log_blessing_moon");
        localizeIDs.Add("log_spirit_born");
        localizeIDs.Add("log_spirit_turn");
        localizeIDs.Add("log_witch_shadow");
        localizeIDs.Add("log_witch_white");
        localizeIDs.Add("log_witch_grey");
        localizeIDs.Add("log_cast_energy");
        localizeIDs.Add("log_cast_msg");
        localizeIDs.Add("log_sentinel");
        localizeIDs.Add("spell_data_cost");
        localizeIDs.Add("spell_spirit_banished");
        localizeIDs.Add("spell_banish");
        localizeIDs.Add("spell_bound_witch");
        localizeIDs.Add("spell_bound_spirit");
        localizeIDs.Add("spell_bound_null");
        localizeIDs.Add("spell_silenced_witch");
        localizeIDs.Add("spell_silenced_spirit");
        localizeIDs.Add("spell_silenced_null");
        localizeIDs.Add("generic_ok");
        localizeIDs.Add("generic_try_again");
        localizeIDs.Add("generic_error");
        localizeIDs.Add("coven_founder");
        localizeIDs.Add("coven_creation");
        localizeIDs.Add("coven_pop_controlled");
        localizeIDs.Add("coven_shadow");
        localizeIDs.Add("coven_white");
        localizeIDs.Add("coven_grey");
        localizeIDs.Add("coven_unally");
        localizeIDs.Add("coven_ally");
        localizeIDs.Add("coven_member_new");
        localizeIDs.Add("coven_invite_revoked");
        localizeIDs.Add("active_days");
        localizeIDs.Add("active_hours");
        localizeIDs.Add("active_mins");
        localizeIDs.Add("active_secs");
        localizeIDs.Add("active_word");
        localizeIDs.Add("log_chat_ally");
        localizeIDs.Add("log_chat_ally_revoke");
        localizeIDs.Add("log_chat_ally_declare");
        localizeIDs.Add("log_chat_coven_unally");
        localizeIDs.Add("coven_expell");
        localizeIDs.Add("log_chat_member_request");
        localizeIDs.Add("coven_player_promoted");
        localizeIDs.Add("log_chat_member_promote");
        localizeIDs.Add("log_chat_titled");
        localizeIDs.Add("log_chat_entitled");
        localizeIDs.Add("coven_member_new_title");
        localizeIDs.Add("log_chat_coven_join");
        localizeIDs.Add("log_chat_coven_abandon");
        localizeIDs.Add("log_chat_coven_invite");
        localizeIDs.Add("log_chat_coven_disband");
        localizeIDs.Add("lt_coven_none");
        localizeIDs.Add("lt_state_normal");
        localizeIDs.Add("lt_state");
        localizeIDs.Add("store_gear_purchase_upper");
        localizeIDs.Add("store_ingredients");
        localizeIDs.Add("store_purchase_info_inventory");
        localizeIDs.Add("office_welcome");
        localizeIDs.Add("office_of_grey");
        localizeIDs.Add("office_turn_in");
        localizeIDs.Add("office_forbidden");
        localizeIDs.Add("office_be_given");
        localizeIDs.Add("spirit_discovered_num");
        localizeIDs.Add("spirit_undiscovered");
        localizeIDs.Add("spirit_discovered");
        localizeIDs.Add("ftf_spawn_region");
        localizeIDs.Add("ftf_barghest_discovered");
        localizeIDs.Add("ftf_barghest_knowledge");
        localizeIDs.Add("office_remember");
        localizeIDs.Add("raincrow_id");
    }

    #region Localize Constants
    public static string account_4_char = "account_4_char";
    public static string account_name = "account_name";
    public static string account_special_char = "account_special_char";
    public static string add_to_inventory = "add_to_inventory";
    public static string autumn_tribunal_upper = "autumn_tribunal_upper";
    public static string blessing_continue = "blessing_continue";
    public static string blessing_grant = "blessing_grant";
    public static string blessing_honor = "blessing_honor";
    public static string blessing_message = "blessing_message";
    public static string blessing_offices = "blessing_offices";
    public static string blessing_pop = "blessing_pop";
    public static string bos_elixir = "bos_elixir";
    public static string bos_elixir_back = "bos_elixir_back";
    public static string bos_elixir_potion = "bos_elixir_potion";
    public static string bos_title = "bos_title";
    public static string card_spirit_attack_upper = "card_spirit_attack_upper";
    public static string card_spirit_behavior_desc = "card_spirit_behavior_desc";
    public static string card_spirit_behavior_upper = "card_spirit_behavior_upper";
    public static string card_spirit_coven_upper = "card_spirit_coven_upper";
    public static string card_spirit_desc_upper = "card_spirit_desc_upper";
    public static string card_spirit_reward_desc = "card_spirit_reward_desc";
    public static string card_spirit_reward_upper = "card_spirit_reward_upper";
    public static string card_spirit_summoner_upper = "card_spirit_summoner_upper";
    public static string card_witch_cast = "card_witch_cast";
    public static string card_witch_cast_upper = "card_witch_cast_upper";
    public static string card_witch_dominion = "card_witch_dominion";
    public static string card_witch_domRank = "card_witch_domRank";
    public static string card_witch_energy = "card_witch_energy";
    public static string card_witch_grey = "card_witch_grey";
    public static string card_witch_level = "card_witch_level";
    public static string card_witch_noCoven = "card_witch_noCoven";
    public static string card_witch_shadow = "card_witch_shadow";
    public static string card_witch_white = "card_witch_white";
    public static string card_witch_worldRank = "card_witch_worldRank";
    public static string cast_crit = "cast_crit";
    public static string cast_death = "cast_death";
    public static string cast_energy = "cast_energy";
    public static string cast_grey = "cast_grey";
    public static string cast_level = "cast_level";
    public static string cast_screen_no_coven = "cast_screen_no_coven";
    public static string cast_screen_request = "cast_screen_request";
    public static string cast_shadow = "cast_shadow";
    public static string cast_spirit_greater = "cast_spirit_greater";
    public static string cast_spirit_legendary = "cast_spirit_legendary";
    public static string cast_spirit_lesser = "cast_spirit_lesser";
    public static string cast_spirit_superior = "cast_spirit_superior";
    public static string cast_spirit_type = "cast_spirit_type";
    public static string cast_white = "cast_white";
    public static string cast_you = "cast_you";
    public static string change_wardrobe = "change_wardrobe";
    public static string character_4_char = "character_4_char";
    public static string character_empty = "character_empty";
    public static string character_name = "character_name";
    public static string character_taken = "character_taken";
    public static string chat_coven = "chat_coven";
    public static string chat_degree = "chat_degree";
    public static string chat_dominion = "chat_dominion";
    public static string chat_go_to_location = "chat_go_to_location";
    public static string chat_grey = "chat_grey";
    public static string chat_news = "chat_news";
    public static string chat_settings = "chat_settings";
    public static string chat_shadow = "chat_shadow";
    public static string chat_share_location = "chat_share_location";
    public static string chat_shout = "chat_shout";
    public static string chat_shoutMessage = "chat_shoutMessage";
    public static string chat_state_trouble = "chat_state_trouble";
    public static string chat_time_ago_days = "chat_time_ago_days";
    public static string chat_time_ago_mins = "chat_time_ago_mins";
    public static string chat_time_ago_seconds = "chat_time_ago_seconds";
    public static string chat_time_ago_weeks = "chat_time_ago_weeks";
    public static string chat_time_ago_years = "chat_time_ago_years";
    public static string chat_translate = "chat_translate";
    public static string chat_white = "chat_white";
    public static string chat_world = "chat_world";
    public static string choose_gender = "choose_gender";
    public static string choose_upper = "choose_upper";
    public static string collect = "collect";
    public static string collecting = "collecting";
    public static string contact_support = "contact_support";
    public static string contact_support_upper = "contact_support_upper";
    public static string continue_generic = "continue_generic";
    public static string continue_upper = "continue_upper";
    public static string continue_without_tutorial = "continue_without_tutorial";
    public static string coven_invite_choose = "coven_invite_choose";
    public static string coven_invite_continue = "coven_invite_continue";
    public static string coven_invite_enter_text = "coven_invite_enter_text";
    public static string coven_screen_allied = "coven_screen_allied";
    public static string coven_screen_coven_allied = "coven_screen_coven_allied";
    public static string coven_screen_create = "coven_screen_create";
    public static string coven_screen_invite = "coven_screen_invite";
    public static string coven_screen_level = "coven_screen_level";
    public static string coven_screen_name = "coven_screen_name";
    public static string coven_screen_nothing = "coven_screen_nothing";
    public static string coven_screen_request = "coven_screen_request";
    public static string create_upper = "create_upper";
    public static string daily_event_log = "daily_event_log";
    public static string daily_explore = "daily_explore";
    public static string daily_gather = "daily_gather";
    public static string daily_hide = "daily_hide";
    public static string daily_spell = "daily_spell";
    public static string daily_spell_completion = "daily_spell_completion";
    public static string daily_spell_title = "daily_spell_title";
    public static string daily_tap_chest = "daily_tap_chest";
    public static string daily_title = "daily_title";
    public static string days_remain = "days_remain";
    public static string dominion_location = "dominion_location";
    public static string download = "download";
    public static string email = "email";
    public static string empty_email = "empty_email";
    public static string enter_code_upper = "enter_code_upper";
    public static string enter_digit_code_email = "enter_digit_code_email";
    public static string enter_password_upper = "enter_password_upper";
    public static string female = "female";
    public static string flight_physical_form = "flight_physical_form";
    public static string flight_spirit_form = "flight_spirit_form";
    public static string forgot_password = "forgot_password";
    public static string ftf_her = "ftf_her";
    public static string ftf_him = "ftf_him";
    public static string ftf_he = "ftf_he";
    public static string ftf_she = "ftf_she";
    public static string ftf_his = "ftf_his";
    public static string ftf_summer = "ftf_summer";
    public static string ftf_winter = "ftf_winter";
    public static string ftf_autumn = "ftf_autumn";
    public static string ftf_spring = "ftf_spring";
    public static string generic_no = "generic_no";
    public static string generic_yes = "generic_yes";
    public static string help_call_crows = "help_call_crows";
    public static string help_call_crows_confirm = "help_call_crows_confirm";
    public static string help_logged_in = "help_logged_in";
    public static string incorrect_username = "incorrect_username";
    public static string internet_error = "internet_error";
    public static string invalid_char = "invalid_char";
    public static string leveled_continue = "leveled_continue";
    public static string leveled_number = "leveled_number";
    public static string leveled_up = "leveled_up";
    public static string loading = "loading";
    public static string location_error = "location_error";
    public static string login_back = "login_back";
    public static string login_create_appropriate = "login_create_appropriate";
    public static string login_past_player_account = "login_past_player_account";
    public static string login_welcome_witch = "login_welcome_witch";
    public static string male = "male";
    public static string Name = "name";
    public static string no_email = "no_email";
    public static string tip = "tip";
    public static string original_sound = "original_sound";
    public static string password = "password";
    public static string password_4_char = "password_4_char";
    public static string pop_required_ingredients = "pop_required_ingredients";
    public static string pop_add_ingredients = "pop_add_ingredients";
    public static string pop_owner_coven = "pop_owner_coven";
    public static string pop_owner_player = "pop_owner_player";
    public static string pop_unclaimed = "pop_unclaimed";
    public static string pop_hint = "pop_hint";
    public static string pop_full = "pop_full";
    public static string pop_enter = "pop_enter";
    public static string pop_enter_no = "pop_enter_no";
    public static string pop_title = "pop_title";
    public static string portal_cast = "portal_cast";
    public static string portal_energy_channel = "portal_energy_channel";
    public static string portal_fly_to = "portal_fly_to";
    public static string portal_ingredient_add = "portal_ingredient_add";
    public static string portal_ingredient_used = "portal_ingredient_used";
    public static string portal_last_attacked = "portal_last_attacked";
    public static string portal_type_lesser = "portal_type_lesser";
    public static string portal_not_enough = "portal_not_enough";
    public static string portal_summon_in = "portal_summon_in";
    public static string portal_summon_spirit = "portal_summon_spirit";
    public static string portal_time_hour = "portal_time_hour";
    public static string portal_time_minute = "portal_time_minute";
    public static string portal_time_second = "portal_time_second";
    public static string portal_create = "portal_create";
    public static string portal_time_remaining = "portal_time_remaining";
    public static string portal_destroy = "portal_destroy";
    public static string portal_trace = "portal_trace";
    public static string privacy_policy = "privacy_policy";
    public static string raincrow_studios = "raincrow_studios";
    public static string re_enter_password = "re_enter_password";
    public static string reset = "reset";
    public static string reset_account_name = "reset_account_name";
    public static string reset_bad_code = "reset_bad_code";
    public static string reset_button = "reset_button";
    public static string reset_enter_code = "reset_enter_code";
    public static string reset_password = "reset_password";
    public static string reset_upper = "reset_upper";
    public static string reset_user_invalid = "reset_user_invalid";
    public static string savannah_upper = "savannah_upper";
    public static string school_skip = "school_skip";
    public static string school_title = "school_title";
    public static string school_watch = "school_watch";
    public static string server_down_bottom = "server_down_bottom";
    public static string server_down_top = "server_down_top";
    public static string server_syncing = "server_syncing";
    public static string sign_in = "sign_in";
    public static string sign_in_existing = "sign_in_existing";
    public static string spell_alignment_change = "spell_alignment_change";
    public static string spell_cancel = "spell_cancel";
    public static string spell_bind = "spell_bind";
    public static string spell_cast = "spell_cast";
    public static string spell_cast_attacked = "spell_cast_attacked";
    public static string spell_cast_backfire = "spell_cast_backfire";
    public static string spell_cast_backfire_yours = "spell_cast_backfire_yours";
    public static string spell_cast_cancel = "spell_cast_cancel";
    public static string spell_cast_success = "spell_cast_success";
    public static string spell_cast_summon = "spell_cast_summon";
    public static string spell_clear_gem = "spell_clear_gem";
    public static string spell_clear_herb = "spell_clear_herb";
    public static string spell_clear_tool = "spell_clear_tool";
    public static string spell_cost = "spell_cost";
    public static string spell_dead = "spell_dead";
    public static string spell_degree_gray = "spell_degree_gray";
    public static string spell_degree_shadow = "spell_degree_shadow";
    public static string spell_degree_white = "spell_degree_white";
    public static string spell_empower = "spell_empower";
    public static string spell_escape_upper = "spell_escape_upper";
    public static string spell_fail = "spell_fail";
    public static string spell_fail_yours = "spell_fail_yours";
    public static string spell_fizzle = "spell_fizzle";
    public static string spell_fizzle_yours = "spell_fizzle_yours";
    public static string spell_immune = "spell_immune";
    public static string spell_immune_to_you = "spell_immune_to_you";
    public static string spell_increase = "spell_increase";
    public static string spell_ingredient_for_me = "spell_ingredient_for_me";
    public static string spell_ingredient_tap_choose = "spell_ingredient_tap_choose";
    public static string spell_ingredient_wise = "spell_ingredient_wise";
    public static string spell_invalid = "spell_invalid";
    public static string spell_sig_discover = "spell_sig_discover";
    public static string spell_tap_ingredient_add = "spell_tap_ingredient_add";
    public static string spell_tap_tool_title = "spell_tap_tool_title";
    public static string spell_xp = "spell_xp";
    public static string spirit_active = "spirit_active";
    public static string spirit_active_none = "spirit_active_none";
    public static string spirit_deck_expire = "spirit_deck_expire";
    public static string spirit_deck_fly_to = "spirit_deck_fly_to";
    public static string spirit_deck_ingredients = "spirit_deck_ingredients";
    public static string spirit_deck_none = "spirit_deck_none";
    public static string spirit_deck_unknown = "spirit_deck_unknown";
    public static string spirit_deck_xp_gained = "spirit_deck_xp_gained";
    public static string spirit_discover_date = "spirit_discover_date";
    public static string spirit_gain = "spirit_gain";
    public static string spirit_known = "spirit_known";
    public static string spirit_known_none = "spirit_known_none";
    public static string spirit_portal = "spirit_portal";
    public static string spirit_portal_none = "spirit_portal_none";
    public static string spirit_use_tool = "spirit_use_tool";
    public static string spirit_was_banished = "spirit_was_banished";
    public static string spring_tribunal_upper = "spring_tribunal_upper";
    public static string start_new = "start_new";
    public static string store_accept = "store_accept";
    public static string store_balance = "store_balance";
    public static string store_bought_drachs_upper = "store_bought_drachs_upper";
    public static string store_buy = "store_buy";
    public static string store_buy_gold = "store_buy_gold";
    public static string store_buy_silver = "store_buy_silver";
    public static string store_buy_upper = "store_buy_upper";
    public static string store_cancel_upper = "store_cancel_upper";
    public static string store_confirm_upper = "store_confirm_upper";
    public static string store_cost = "store_cost";
    public static string store_current = "store_current";
    public static string store_elixir = "store_elixir";
    public static string store_elixir_more = "store_elixir_more";
    public static string store_elixir_upper = "store_elixir_upper";
    public static string store_gear = "store_gear";
    public static string store_gear_accessories = "store_gear_accessories";
    public static string store_gear_clothing = "store_gear_clothing";
    public static string store_gear_hairstyle = "store_gear_hairstyle";
    public static string store_gear_or = "store_gear_or";
    public static string store_gear_or_upper = "store_gear_or_upper";
    public static string store_gear_owned_upper = "store_gear_owned_upper";
    public static string store_gear_skin_art = "store_gear_skin_art";
    public static string store_gear_unlock_upper = "store_gear_unlock_upper";
    public static string store_gear_unlocked_upper = "store_gear_unlocked_upper";
    public static string store_gear_upper = "store_gear_upper";
    public static string store_more_silver = "store_more_silver";
    public static string store_not_enough_gold = "store_not_enough_gold";
    public static string store_not_enough_silver = "store_not_enough_silver";
    public static string store_preview = "store_preview";
    public static string store_purchase_successful = "store_purchase_successful";
    public static string store_purchase_unsuccessful = "store_purchase_unsuccessful";
    public static string store_silver = "store_silver";
    public static string store_silver_drachs_upper = "store_silver_drachs_upper";
    public static string store_silver_no_buy = "store_silver_no_buy";
    public static string store_silver_upper = "store_silver_upper";
    public static string strongest_coven_dominion = "strongest_coven_dominion";
    public static string strongest_witch_dominion = "strongest_witch_dominion";
    public static string summer_tribunal_upper = "summer_tribunal_upper";
    public static string summoning_add_gems_botanicals = "summoning_add_gems_botanicals";
    public static string summoning_botanicals_upper = "summoning_botanicals_upper";
    public static string summoning_cast_upper = "summoning_cast_upper";
    public static string summoning_clear = "summoning_clear";
    public static string summoning_created_by = "summoning_created_by";
    public static string summoning_destroy = "summoning_destroy";
    public static string summoning_empower = "summoning_empower";
    public static string summoning_gems_upper = "summoning_gems_upper";
    public static string summoning_please_select = "summoning_please_select";
    public static string summoning_portal = "summoning_portal";
    public static string summoning_portal_attack = "summoning_portal_attack";
    public static string summoning_portal_summon_time = "summoning_portal_summon_time";
    public static string summoning_select_tool = "summoning_select_tool";
    public static string summoning_spirit_summon_time = "summoning_spirit_summon_time";
    public static string summoning_tools_upper = "summoning_tools_upper";
    public static string summoning_trace_circle = "summoning_trace_circle";
    public static string update_app = "update_app";
    public static string username_taken = "username_taken";
    public static string winter_tribunal_upper = "winter_tribunal_upper";
    public static string witch_name = "witch_name";
    public static string witch_school_title = "witch_school_title";
    public static string invite_send = "invite_send";
    public static string invite_failed = "invite_failed";
    public static string invite_coven = "invite_coven";
    public static string ftf_you_map = "ftf_you_map";
    public static string ftf_gained_power = "ftf_gained_power";
    public static string ftf_known_spirits = "ftf_known_spirits";
    public static string ftf_active_spirits = "ftf_active_spirits";
    public static string ftf_active_portals = "ftf_active_portals";
    public static string ftf_reward_upper = "ftf_reward_upper";
    public static string ftf_reward_capture = "ftf_reward_capture";
    public static string ftf_behavior_upper = "ftf_behavior_upper";
    public static string ftf_description_upper = "ftf_description_upper";
    public static string ftf_wild_spirit = "ftf_wild_spirit";
    public static string ftf_attack_button = "ftf_attack_button";
    public static string ftf_brigid_degree_upper = "ftf_brigid_degree_upper";
    public static string ftf_brigid_school_upper = "ftf_brigid_school_upper";
    public static string ftf_invite_to_coven = "ftf_invite_to_coven";
    public static string ftf_theo_consume = "ftf_theo_consume";
    public static string ftf_silenced_by = "ftf_silenced_by";
    public static string ftf_silenced = "ftf_silenced";
    public static string ftf_dispel = "ftf_dispel";
    public static string ftf_silence_dispel = "ftf_silence_dispel";
    public static string ftf_died = "ftf_died";
    public static string ftf_banish_brigid = "ftf_banish_brigid";
    public static string ftf_banish = "ftf_banish";
    public static string ftf_claim = "ftf_claim";
    public static string ftf_buy_silver = "ftf_buy_silver";
    public static string ftf_not_enough = "ftf_not_enough";
    public static string ftf_continue = "ftf_continue";
    public static string ftf_success = "ftf_success";
    public static string ftf_show_school = "ftf_show_school";
    public static string ftf_no_education = "ftf_no_education";
    public static string ftf_continue_game = "ftf_continue_game";
    public static string ftf_cast_button = "ftf_cast_button";
    public static string ftf_immune_upper = "ftf_immune_upper";
    public static string ftf_brigid = "ftf_brigid";
    public static string ftf_barghest_tier = "ftf_barghest_tier";
    public static string ftf_barghest = "ftf_barghest";
    public static string ftf_world_upper = "ftf_world_upper";
    public static string ftf_barghest_type = "ftf_barghest_type";
    public static string ftf_barghest_behavior = "ftf_barghest_behavior";
    public static string ftf_barghest_behavior_detailed = "ftf_barghest_behavior_detailed";
    public static string ftf_barghest_description = "ftf_barghest_description";
    public static string ftf_barghest_tier_one = "ftf_barghest_tier_one";
    public static string ftf_barghest_lesser = "ftf_barghest_lesser";
    public static string ftf_barghest_wild = "ftf_barghest_wild";
    public static string ftf_world = "ftf_world";
    public static string ftf_one = "ftf_one";
    public static string ftf_eight = "ftf_eight";
    public static string ftf_brigid_energy = "ftf_brigid_energy";
    public static string ftf_cast_dusk = "ftf_cast_dusk";
    public static string ftf_buy_best = "ftf_buy_best";
    public static string ftf_brigid_mad = "ftf_brigid_mad";
    public static string ftf_best_description = "ftf_best_description";
    public static string ftf_best_cost = "ftf_best_cost";
    public static string ftf_best = "ftf_best";
    public static string character_signature_new = "character_signature_new";
    public static string spell_cast_success_yours = "spell_cast_success_yours";
    public static string spell_cast_energy_sap = "spell_cast_energy_sap";
    public static string spell_cast_backfire_theirs = "spell_cast_backfire_theirs";
    public static string spirit_banished = "spirit_banished";
    public static string lt_energy = "lt_energy";
    public static string lt_none = "lt_none";
    public static string lt_portal = "lt_portal";
    public static string lt_summon_in = "lt_summon_in";
    public static string lt_level = "lt_level";
    public static string lt_dominion = "lt_dominion";
    public static string lt_dominion_rank = "lt_dominion_rank";
    public static string lt_world_rank = "lt_world_rank";
    public static string lt_coven = "lt_coven";
    public static string lt_invite_sent = "lt_invite_sent";
    public static string lt_invite_sent_already = "lt_invite_sent_already";
    public static string pop_defended = "pop_defended";
    public static string lt_spirit_s = "lt_spirit_s";
    public static string lt_spirit_p = "lt_spirit_p";
    public static string lt_close = "lt_close";
    public static string pop_treasure_time = "pop_treasure_time";
    public static string lt_silenced = "lt_silenced";
    public static string lt_time_days = "lt_time_days";
    public static string lt_time_day = "lt_time_day";
    public static string lt_time_hours = "lt_time_hours";
    public static string lt_time_hour = "lt_time_hour";
    public static string lt_time_minutes = "lt_time_minutes";
    public static string lt_unkown = "lt_unkown";
    public static string lt_time_minute = "lt_time_minute";
    public static string lt_time_seconds = "lt_time_seconds";
    public static string lt_time_secs = "lt_time_secs";
    public static string server_connect = "server_connect";
    public static string store_buy_energy = "store_buy_energy";
    public static string consume_amount = "consume_amount";
    public static string show_dominion = "show_dominion";
    public static string blessing_time = "blessing_time";
    public static string ingredient_gems = "ingredient_gems";
    public static string ingredient_botanicals = "ingredient_botanicals";
    public static string ingredient_tools = "ingredient_tools";
    public static string spell_tap_herbs_none = "spell_tap_herbs_none";
    public static string spell_tap_tools_none = "spell_tap_tools_none";
    public static string spell_tap_gems_none = "spell_tap_gems_none";
    public static string chat_player_level = "chat_player_level";
    public static string chat_translate_language = "chat_translate_language";
    public static string lt_failed = "lt_failed";
    public static string chat_screen_no_coven = "chat_screen_no_coven";
    public static string invite_request = "invite_request";
    public static string coven_create_name_used = "coven_create_name_used";
    public static string coven_create_name_invalid = "coven_create_name_invalid";
    public static string coven_create_name_empty = "coven_create_name_empty";
    public static string coven_request_name = "coven_request_name";
    public static string coven_request_success = "coven_request_success";
    public static string coven_request_sent = "coven_request_sent";
    public static string coven_request_full = "coven_request_full";
    public static string coven_request_null = "coven_request_null";
    public static string coven_invite = "coven_invite";
    public static string coven_invite_success = "coven_invite_success";
    public static string coven_invite_sent = "coven_invite_sent";
    public static string coven_invite_null = "coven_invite_null";
    public static string coven_null_authorized = "coven_null_authorized";
    public static string coven_invite_empty = "coven_invite_empty";
    public static string coven_invite_join = "coven_invite_join";
    public static string coven_invite_join_success = "coven_invite_join_success";
    public static string coven_invite_cancelled = "coven_invite_cancelled";
    public static string coven_disbanded = "coven_disbanded";
    public static string coven_decline_invite = "coven_decline_invite";
    public static string coven_decline_invite_success = "coven_decline_invite_success";
    public static string coven_invite_cancel = "coven_invite_cancel";
    public static string coven_invite_cancel_success = "coven_invite_cancel_success";
    public static string coven_leave = "coven_leave";
    public static string coven_leave_success = "coven_leave_success";
    public static string coven_disband = "coven_disband";
    public static string coven_disband_success = "coven_disband_success";
    public static string coven_member_promote = "coven_member_promote";
    public static string coven_member_promote_success = "coven_member_promote_success";
    public static string coven_member_remove = "coven_member_remove";
    public static string coven_member_remove_success = "coven_member_remove_success";
    public static string coven_motto = "coven_motto";
    public static string coven_motto_set = "coven_motto_set";
    public static string pop_rewards_silver = "pop_rewards_silver";
    public static string pop_rewards_gold = "pop_rewards_gold";
    public static string pop_rewards_energy = "pop_rewards_energy";
    public static string header_pop = "header_pop";
    public static string header_invites_players = "header_invites_players";
    public static string header_requests = "header_requests";
    public static string header_allies = "header_allies";
    public static string header_allied = "header_allied";
    public static string header_invites = "header_invites";
    public static string header_no_coven = "header_no_coven";
    public static string ui_drink_potion = "ui_drink_potion";
    public static string apparel_head = "apparel_head";
    public static string apparel_hair = "apparel_hair";
    public static string apparel_neck = "apparel_neck";
    public static string apparel_chest = "apparel_chest";
    public static string apparel_wrist = "apparel_wrist";
    public static string apparel_hands = "apparel_hands";
    public static string apparel_legs = "apparel_legs";
    public static string apparel_feet = "apparel_feet";
    public static string apparel_carry = "apparel_carry";
    public static string apparel_tattoo = "apparel_tattoo";
    public static string rarity_common = "rarity_common";
    public static string rarity_less = "rarity_less";
    public static string rarity_rare = "rarity_rare";
    public static string rarity_exotic = "rarity_exotic";
    public static string rarity_num = "rarity_num";
    public static string add_to_inventory_fail = "add_to_inventory_fail";
    public static string inventory_tool = "inventory_tool";
    public static string inventory_missing = "inventory_missing";
    public static string summoning_success = "summoning_success";
    public static string summoning_time = "summoning_time";
    public static string error_unknown = "error_unknown";
    public static string spell_player_immune = "spell_player_immune";
    public static string kyteler_owned = "kyteler_owned";
    public static string kyteler_last_location = "kyteler_last_location";
    public static string kyteler_date_discovered = "kyteler_date_discovered";
    public static string leaderboard_coven = "leaderboard_coven";
    public static string leaderboard_player = "leaderboard_player";
    public static string location_owned = "location_owned";
    public static string location_unclaimed = "location_unclaimed";
    public static string login_error = "login_error";
    public static string login_retry = "login_retry";
    public static string account_creation_username_invalid = "account_creation_username_invalid";
    public static string account_creation_session_expired = "account_creation_session_expired";
    public static string account_creation_email_invalid = "account_creation_email_invalid";
    public static string account_creation_error = "account_creation_error";
    public static string character_special_char = "character_special_char";
    public static string character_name_invalid = "character_name_invalid";
    public static string character_error = "character_error";
    public static string password_no_match = "password_no_match";
    public static string ui_response_spell = "ui_response_spell";
    public static string ui_response_portal = "ui_response_portal";
    public static string ui_response_move_closer = "ui_response_move_closer";
    public static string ui_response_summon = "ui_response_summon";
    public static string ui_response_backfire = "ui_response_backfire";
    public static string ui_response_shadow = "ui_response_shadow";
    public static string ui_response_white = "ui_response_white";
    public static string ui_response_grey = "ui_response_grey";
    public static string ui_response_witch = "ui_response_witch";
    public static string ui_response_spirit = "ui_response_spirit";
    public static string ui_response_spirit_discovered = "ui_response_spirit_discovered";
    public static string ui_response_discovered = "ui_response_discovered";
    public static string spell_target = "spell_target";
    public static string spell_target_lose_energy = "spell_target_lose_energy";
    public static string spell_target_gain_energy = "spell_target_gain_energy";
    public static string attacked_message = "attacked_message";
    public static string attacked_spirit = "attacked_spirit";
    public static string item_loading = "item_loading";
    public static string moon_rise = "moon_rise";
    public static string moon_new = "moon_new";
    public static string moon_wax_cresc = "moon_wax_cresc";
    public static string moon_first_quart = "moon_first_quart";
    public static string moon_wax_gib = "moon_wax_gib";
    public static string moon_full = "moon_full";
    public static string moon_wan_gib = "moon_wan_gib";
    public static string moon_last_quart = "moon_last_quart";
    public static string moon_wan_cresc = "moon_wan_cresc";
    public static string moon_relation = "moon_relation";
    public static string moon_desc = "moon_desc";
    public static string moon_energy = "moon_energy";
    public static string log_blessing_savannah = "log_blessing_savannah";
    public static string log_blessing_moon = "log_blessing_moon";
    public static string log_spirit_born = "log_spirit_born";
    public static string log_spirit_turn = "log_spirit_turn";
    public static string log_witch_shadow = "log_witch_shadow";
    public static string log_witch_white = "log_witch_white";
    public static string log_witch_grey = "log_witch_grey";
    public static string log_cast_energy = "log_cast_energy";
    public static string log_cast_msg = "log_cast_msg";
    public static string log_sentinel = "log_sentinel";
    public static string spell_data_cost = "spell_data_cost";
    public static string spell_spirit_banished = "spell_spirit_banished";
    public static string spell_banish = "spell_banish";
    public static string spell_bound_witch = "spell_bound_witch";
    public static string spell_bound_spirit = "spell_bound_spirit";
    public static string spell_bound_null = "spell_bound_null";
    public static string spell_silenced_witch = "spell_silenced_witch";
    public static string spell_silenced_spirit = "spell_silenced_spirit";
    public static string spell_silenced_null = "spell_silenced_null";
    public static string generic_ok = "generic_ok";
    public static string generic_try_again = "generic_try_again";
    public static string generic_error = "generic_error";
    public static string coven_founder = "coven_founder";
    public static string coven_creation = "coven_creation";
    public static string coven_pop_controlled = "coven_pop_controlled";
    public static string coven_shadow = "coven_shadow";
    public static string coven_white = "coven_white";
    public static string coven_grey = "coven_grey";
    public static string coven_unally = "coven_unally";
    public static string coven_ally = "coven_ally";
    public static string coven_member_new = "coven_member_new";
    public static string coven_invite_revoked = "coven_invite_revoked";
    public static string active_days = "active_days";
    public static string active_hours = "active_hours";
    public static string active_mins = "active_mins";
    public static string active_secs = "active_secs";
    public static string active_word = "active_word";
    public static string log_chat_ally = "log_chat_ally";
    public static string log_chat_ally_revoke = "log_chat_ally_revoke";
    public static string log_chat_ally_declare = "log_chat_ally_declare";
    public static string log_chat_coven_unally = "log_chat_coven_unally";
    public static string coven_expell = "coven_expell";
    public static string log_chat_member_request = "log_chat_member_request";
    public static string coven_player_promoted = "coven_player_promoted";
    public static string log_chat_member_promote = "log_chat_member_promote";
    public static string log_chat_titled = "log_chat_titled";
    public static string log_chat_entitled = "log_chat_entitled";
    public static string coven_member_new_title = "coven_member_new_title";
    public static string log_chat_coven_join = "log_chat_coven_join";
    public static string log_chat_coven_abandon = "log_chat_coven_abandon";
    public static string log_chat_coven_invite = "log_chat_coven_invite";
    public static string log_chat_coven_disband = "log_chat_coven_disband";
    public static string lt_coven_none = "lt_coven_none";
    public static string lt_state_normal = "lt_state_normal";
    public static string lt_state = "lt_state";
    public static string store_gear_purchase_upper = "store_gear_purchase_upper";
    public static string store_ingredients = "store_ingredients";
    public static string store_purchase_info_inventory = "store_purchase_info_inventory";
    public static string office_welcome = "office_welcome";
    public static string office_of_grey = "office_of_grey";
    public static string office_turn_in = "office_turn_in";
    public static string office_forbidden = "office_forbidden";
    public static string office_be_given = "office_be_given";
    public static string spirit_discovered_num = "spirit_discovered_num";
    public static string spirit_undiscovered = "spirit_undiscovered";
    public static string spirit_discovered = "spirit_discovered";
    public static string ftf_spawn_region = "ftf_spawn_region";
    public static string ftf_barghest_discovered = "ftf_barghest_discovered";
    public static string ftf_barghest_knowledge = "ftf_barghest_knowledge";
    public static string office_remember = "office_remember";
    public static string raincrow_id = "raincrow_id";
    #endregion

}


